# Python的科学计算包 - Numpy

**Numerical Python extensions**是一个第三方的Python包，用于科学计算。目前已经成为绝大部分Python科学计算的基础包。

https://zhuanlan.zhihu.com/p/24309547

----

## 1. 基本类型（Array）

在Numpy中可以非常方便的创建各种不同类型的张量（Tensor），并且执行一些基本操作。

### 1.1 一维数组

In [1]:
# 按照惯例，numpy使用别名np
import numpy as np

In [2]:
# 用列表生成numpy的数组
a = [1, 2, 3, 4]
b = np.array(a)
type(b)

numpy.ndarray

In [3]:
# 输出数组的形状
b.shape

(4,)

In [4]:
# 返回最大的索引值
b.argmax()

3

In [5]:
# 最大值
b.max()

4

In [6]:
# 均值
b.mean()

2.5

### 1.2 二维数组
$$ \begin{bmatrix} 1 & 2 \\ 3 & 4 \end{bmatrix} $$

In [7]:
c = [[1, 2], [3, 4]]
d = np.array(c)
d

array([[1, 2],
       [3, 4]])

In [8]:
d.shape

(2, 2)

In [9]:
d.size

4

In [10]:
d.max(axis = 0)

array([3, 4])

In [11]:
d.max(axis=1)

array([2, 4])

In [12]:
d.mean(axis=0)

array([ 2.,  3.])

In [13]:
# 将数组展开为一个1维数组
d.flatten()

array([1, 2, 3, 4])

In [14]:
# 返回一个1维的数组
np.ravel(c)

array([1, 2, 3, 4])

### 1.3 利用Numpy产生数组

Numpy中包含很多用来生成数组的函数。

In [16]:
e = np.ones((3, 3), dtype=np.float)
e

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [18]:
f = np.repeat(3, 4)
f

array([3, 3, 3, 3])

In [23]:
# 创建一个2*2*3的张量
g = np.zeros((2, 2, 3), dtype=np.uint8)
g.shape

(2, 2, 3)

In [25]:
h = g.astype(np.float)
h

array([[[ 0.,  0.,  0.],
        [ 0.,  0.,  0.]],

       [[ 0.,  0.,  0.],
        [ 0.,  0.,  0.]]])

In [30]:
# 类似于range函数
l = np.arange(10)
l

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
# 在0到6之间取5个数
m = np.linspace(0, 6, 5)
m

array([ 0. ,  1.5,  3. ,  4.5,  6. ])

In [32]:
# save and load
p = np.array(
    [[1, 2, 3, 4],
     [5, 6, 7, 8]]
)

np.save('p.npy', p)
q = np.load('p.npy')
q

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])